services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stockflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - stockflow-sqldata:/var/opt/mssql

volumes:
  stockflow-sqldata:
